### ISSUE TITLE
Pagination and sorting with tables

### ISSUE THREAD

**Issue by agilvarry** [utahdts/utah-design-system#235]
Is there a plan to implement sorting across the entirety of paginated tables?

I implemented both today in my app and noticed that sorting only applies to the current page, but I know users will probably expect column sorting to be across every page of the table.

**Comment by AustinHaws-Utah** [comment]
YES! We noticed this too. 

The Pagination component is fighting with filtering and sorting because pagination doesn't know about filtering and sorting. But now there is a a TableContextConsumer component  which can provide all the state of the table to things like Pagination.

```javascript
<TableWrapper>
  <Table>...all the table stuff...</Table>
  <TableContextConsumer>
    {(tableContext) => {
      ...prep for pagination from table context information including sorting/filtering...
      return <Pagination {...use prepped values...} />
    }}
  </TableContextConsumer>
</TableWrapper>
```

This sprint we have a task, UDS-1186, to show how to tie Pagination in to the Table context in order to have filtering and sorting work with pagination. There is a bit of discovery involved here to make sure the context and pagination will now be able to play nice, but we're optimistic this will produce working results.

**Comment by agilvarry** [comment]
Following this up since you mentioned you had a sprint task to address this. Were you able to resolve the issue?

**Comment by AustinHaws-Utah** [comment]
Glad you followed up! It's in our current sprint, but marked as blocked. We hit a snag with the complexity of tracking state between the table and outside the table for filtered results and pagination. Since this sprint is a short one with Thanksgiving, I would predict this getting completed probably start of December.

**Comment by AustinHaws-Utah** [comment]
The new TablePagination component has been released. Pagination for a table using just a plain Pagination component was having all sorts of syncing issues. The new TablePagination component is rendered INSIDE the TableWrapper so it can partake of its context and tie in to the data list in a much more natural methodology.

```
    <TableWrapper>
      <Table>
        <TableBody>
          <TableBodyData records={stateSymbols} recordIdField="category">
            <TableBodyDataRowTemplate>
              <TableBodyDataCellTemplate recordFieldPath="category" />
              <TableBodyDataCellTemplate recordFieldPath="symbol" />
              <TableBodyDataCellTemplate recordFieldPath="year" />
            </TableBodyDataRowTemplate>
          </TableBodyData>
        </TableBody>
      </Table>
      <div className="flex justify-center">
        <TablePagination
          className="mt-spacing"
          id="table-example-render-pagination-id"
          pageSize={5}
        />
      </div>
    </TableWrapper>
```
