### ISSUE TITLE
React Tooltip example

### ISSUE THREAD

**Issue by agilvarry** [utahdts/utah-design-system#243]
The react example for tooltip doesn't work as written. I needed to add `referenceElement={referenceElement.current}` to the props to get it working. I'd also use the Button component in the example for consistency. Maybe something like the below?

```js
const referenceElement = useRef();
...
<Button
  onClick={() => { }}
  innerRef={referenceElement}
  type="button"
>
  <span className="utds-icon-before-gear" aria-hidden="true" />
  <span className="visually-hidden">Gear Icon with Tooltip</span>
</Button>
<Tooltip referenceElement={referenceElement.current}>
  Now you see me
</Tooltip>
```

**Comment by AustinHaws-Utah** [comment]
UDS-1278 was created for this. We plan on having the example updated in this sprint.

One note. The example was showing how to connect a tooltip to any component/element. That's why we used a `button` instead of a `Button`. Totally legitimate to use a `Button`, but we'll probably leave the example as `button`. 

For a Button with a tooltip it may be more correct to use an IconButton which already has a tooltip built in.

We also have future plans to add a `tooltip` attribute to all the components for which it makes sense to have a tooltip.

**Comment by AustinHaws-Utah** [comment]
This has been changed and released.
